base_url = "https://dsatlse.github.io"
title = "LSESU Data Science Society"
highlight_code = true
highlight_theme = "ir-white"
build_search_index = true
taxonomies = [{name = "tags"}]

[extra]
# Empty means none, otherwise renders html,
# e.g. "<strong>IMP</strong> in progress"
# announcement = "This website is under heavy development, the structure might change"
announcement = ""

# Sequence of years, keep in order
years = ["2018", "2019", "2020"]

# Links to social media, keep updated
facebook = "https://www.facebook.com/dsatlse"
lsesu = "https://www.lsesu.com/communities/societies/group/machinelearning/"
github = "https://github.com/dsatlse"
zulip = "https://dsatlse.zulipchat.com"
email = "mailto:data-science@lsesu.org"
linkedin = "https://www.linkedin.com/company/lsesu-data-science-society/"
instagram = "https://www.instagram.com/dsatlse/"
twitter = "https://twitter.com/LSESU_DSS"

